(put 'customize-variable 'disabled nil)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode t)
 '(elfeed-feeds '("http://news4vip.livedoor.biz/index.rdf"))
 '(eradio-channels
   '(("J-AFN 360 Tokyo (Japan Only)" . "https://24873.live.streamtheworld.com/AFNP_TKO_SC")
     ("J-BBC World Service" . "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service")
     ("J-FMうるま" . "https://mtist.as.smartstream.ne.jp/30011/livestream/chunklist.m3u8")
     ("J-JPOP" . "https://kathy.torontocast.com:3560/;")
     ("J-Japan Hits - Asia DREAM Radio" . "http://igor.torontocast.com:1025/;")
     ("J-NHK FM" . "https://radio-stream.nhk.jp/hls/live/2023507/nhkradiruakfm/master48k.m3u8")
     ("J-NHK R1" . "https://radio-stream.nhk.jp/hls/live/2023229/nhkradiruakr1/master48k.m3u8")
     ("J-NHK R2" . "https://radio-stream.nhk.jp/hls/live/2023501/nhkradiruakr2/master48k.m3u8")
     ("J-ビームFM (Beam FM)" . "http://shoutcast.beamfm.net:8508/;")
     ("J-湘南ビーチFM" . "http://shonanbeachfm.out.airtime.pro:8000/shonanbeachfm_a")
     ("J-日経新聞を読んで" . "https://f-radiko.smartstream.ne.jp/RN1/_definst_/simul-stream.stream/chunklist_w1556600463.m3u8")
     ("a-(Channel name not found) " . "http://radio.smallte.ch/test.m3u")
     ("a-(Channel name not found) " . "http://www.anetstation.com/MP3/ANETSTATIONDOTCOM.m3u")
     ("a-- Portofino Network - Italy - Italian Pop Top40 R" . "http://kos.broadstreamer.com:7030/listen.pls")
     ("a-.977 The Comedy Channel - 977MUSIC.COM - The Comedy Internet Radio Channel Comedy Spoken Word Talk" . "http://64.237.49.76:8030/listen.pls")
     ("a-101.5 CJUM-FM - College Eclectic College" . "http://www.umfm.com/umfm.pls")
     ("a-101.5 CJUM-FM - College Eclectic College" . "http://www.umfm.com/umfm_high.pls")
     ("a-181.FM - Classic Hits --- Home of The 60's and 70's Classic Hits 60's 70's" . "http://uplink.duplexfx.com:6108/listen.pls")
     ("a-181.FM - Energy 98 - Dance Hits Dance Hits - Top 40" . "http://mp3uplink.duplexfx.com:9000/listen.pls")
     ("a-181.fm - Awesome 80's 80s Pop Rock Top 40" . "http://uplink.duplexfx.com:8000/listen.pls")
     ("a-1Club.FM - 80s Decade Hits Channel 65k 80s Pop, Dance Rock" . "http://208.53.158.28:9310/listen.pls")
     ("a-1Club.FM - Smooth Jazz Channel Jazz" . "http://208.53.158.28:17510/listen.pls")
     ("a-ACB Radio Mainstream Talk" . "http://www.acbradio.org/mainstream.pls")
     ("a-ACRN.com - The Rock Lobster! College Rock" . "http://132.235.204.252:8000/listen.pls")
     ("a-AM 580 Oldies" . "http://streaming7.wecreate.com:8080/580am.mp3.m3u")
     ("a-Alex Jones - Infowars.com Talk News Political" . "http://www.infowars.com/stream.pls")
     ("a-B96 " . "http://provisioning.streamtheworld.com/pls/WBBMFMDIALUP.pls")
     ("a-BlitzRadio.FM - Electronic Music Radio - 24h ONAIR - Streamed by Blitz-Stream.de Dance Techno Trance House" . "http://server5.blitz-stream.de:9381/listen.pls")
     ("a-CFMU - McMaster University Campus Radio College" . "http://cfmu.wwworks-inc.com:8000/listen.pls")
     ("a-CJSW - University of Calgary Radio college alternative jazz blues country rock punk reggae news world" . "http://stream.cjsw.com/cjsw.mp3.m3u")
     ("a-Classic Electronica - D I G I T A L L Y - I M P O R T E D - old school techno, trance Electronic Techno Trance" . "http://www.di.fm/mp3/classictechno.pls")
     ("a-Cyber-FM 70s and 80s Pop Rock Top 40 Hits 70s 80s Pop Rock Top 40 Hits" . "http://music.cyber-fm.com:8000/Eighties.m3u")
     ("a-Dainbramage Rock" . "http://www.dainbramage.com/listen/listen24.pls")
     ("a-Geetham Radio - 80s 80s Tamil Songs" . "http://www.geethamradio.com:8020/80s_hifi.mp3.m3u")
     ("a-HOME.fm - Spring Arbor University Radio Adult Contemporary" . "http://radio.arbor.edu:7000/listen.pls")
     ("a-Hardcore - D I G I T A L L Y - I M P O R T E D Electronic Hardcore Trance" . "http://www.di.fm/mp3/hardcore.pls")
     ("a-Hardstyle - D I G I T A L L Y - I M P O R T E D - Banging Hardstyle for your ears!!! Electronic Hardstyle Hard Bass" . "http://www.di.fm/mp3/hardstyle.pls")
     ("a-IP music - aacPlus@128 Kb/s Adult Pop Rock 80' Disco Various Mixed Top40 Radio Music" . "http://www.ipmusic.ch/ipmusicaacplus128.m3u")
     ("a-IP music - aacPlus@96 Kb/s Adult Pop Rock 80' Disco Various Mixed Top40 Radio Music" . "http://www.ipmusic.ch/ipmusicaacplus96.m3u")
     ("a-K-EARTH 101 FM " . "http://provisioning.streamtheworld.com/pls/KRTHFMDIALUP.pls")
     ("a-KEXP Live 128kbps Alternative" . "http://kexp-mp3-2.cac.washington.edu:8000/listen.pls")
     ("a-KUOW High Bandwidth Talk" . "http://128.208.34.80:8002/listen.pls")
     ("a-KUWS-Stream College" . "http://137.81.1.91:8000/listen.pls")
     ("a-KVRX Radio 91.7 FM Austin Indie College Rock" . "http://129.116.109.155:8000/listen.pls")
     ("a-M2 RADIO : ONLY HITS AND DANCE - Live From Paris France - www.m2radio.fr Dance House Electronic" . "http://www.m2radio.fr/pls/m2radio.m3u")
     ("a-Marfa Public Radio (KRTS) Public Radio" . "http://amber.streamguys.com:4350/listen.pls")
     ("a-PlasticAge Radio Australia 24k - www.plasticage.com.au Electronic" . "http://sc4.spacialnet.com:21858/listen.pls")
     ("a-Play Two UK 80s 70s 90s Pop British" . "http://audio1.playradiouk.com:9088/listen.pls")
     ("a-RHYTHM 86 Dance House Electronic" . "http://72.8.159.14:9548/listen.pls")
     ("a-RSR - Couleur3 Public Radio" . "http://broadcast.infomaniak.ch/rsr-couleur3-low.mp3.pls")
     ("a-Radio Free Moscow Community FM" . "http://www.radiofreemoscow.com/krfp.m3u")
     ("a-Radio Graffiti Various" . "http://s3.mediastreaming.it:7380/listen.pls")
     ("a-Radio Suisse Classique Classical" . "http://www.radiosuisseclassique.ch/live/aacp32.m3u")
     ("a-Radio Suisse Classique Classical" . "http://www.radiosuisseclassique.ch/live/mp3.m3u")
     ("a-The Joy FM Christian" . "http://209.85.88.199:10040/listen.pls")
     ("a-WPLN-FM NPR-Classical" . "http://wpln.streamguys.org/wplnfm.mp3.m3u")
     ("a-WYPR Public Radio Intro " . "http://www.publicbroadcasting.net/wypr/ppr/wypr.m3u")
     ("a-friskyRadio | feelin' frisky? [Best Dance, House, Trance and Techno] electronic progressive" . "http://www.friskyradio.com/frisky_aac.m3u")
     ("a-friskyRadio | feelin' frisky? progressive house dance" . "http://www.friskyradio.com/frisky_low.m3u")
     ("c-181FM -- THE BEAT (Urban)" . "http://relay.181.fm:8054")
     ("c-cafe - lainon" . "https://lainon.life/radio/cafe.ogg.m3u")
     ("c-cyberia - lainon" . "https://lainon.life/radio/cyberia.ogg.m3u")
     ("c-soma fm def con" . "https://somafm.com/defcon256.pls")
     ("c-soma fm metal" . "https://somafm.com/metal130.pls")
     ("k-Bide 70s 80s 60s pop oldies" . "http://www.bide-et-musique.com/playlist-hq.m3u")
     ("k-Bluemars" . "http://streams.echoesofbluemars.org:8000/bluemars.m3u")
     ("k-Cryosleep" . "http://streams.echoesofbluemars.org:8000/cryosleep.m3u")
     ("k-KALX: UC Berkeley" . "http://stream.kalx.berkeley.edu:8000/kalx-128.mp3")
     ("k-KAOS: Evergreen State" . "http://205.134.192.90:8930/")
     ("k-KCRW" . "http://media.kcrw.com/pls/kcrwsimulcast.pls")
     ("k-KCRW: Eclectic24" . "http://media.kcrw.com/pls/kcrwmusic.pls")
     ("k-KCRW: News24" . "http://media.kcrw.com/pls/kcrwnews.pls")
     ("k-KEXP" . "http://live-mp3-128.kexp.org/")
     ("k-KING: Classical" . "http://classicalking.streamguys1.com/king-fm-mp3")
     ("k-KING: Evergreen" . "http://classicalking.streamguys1.com/evergreen-mp3-96k")
     ("k-KNKX" . "http://live.wostreaming.net/direct/ppm-knkxfmmp3-ibc1")
     ("k-KNKX: Jazz24" . "http://live.wostreaming.net/direct/ppm-jazz24mp3-ibc1")
     ("k-KUOW" . "http://playerservices.streamtheworld.com/pls/KUOWFM_HIGH_MP3.pls")
     ("k-RSR - Couleur3 Public Radio" . "http://broadcast.infomaniak.ch/rsr-couleur3-high.mp3.pls")
     ("k-Voices Within" . "http://streams.echoesofbluemars.org:8000/voicesfromwithin.m3u")
     ("k-WZBC: Boston College" . "http://amber.streamguys.com:4860/")
     ("lionline-Classical" . "http://mediaserv30.live-streams.nl:8088/live")
     ("lionline-France" . "http://mediaserv21.live-streams.nl:8000/live")
     ("lionline-Gold" . "http://mediaserv30.live-streams.nl:8000/live")
     ("lionline-Jazz" . "http://mediaserv38.live-streams.nl:8006/live")
     ("lionline-Latin" . "http://mediaserv33.live-streams.nl:8034/live")
     ("lionline-Lounge" . "http://mediaserv33.live-streams.nl:8036/live")
     ("lionline-Pop" . "http://mediaserv30.live-streams.nl:8086/live")
     ("lionline-World" . "http://mediaserv38.live-streams.nl:8027/live")
     ("triton-am-aac" . "https://www.wxxi.org/sites/default/files/am-aac-triton.m3u")
     ("triton-fm-aac" . "https://www.wxxi.org/sites/default/files/fm-aac-triton.m3u")
     ("triton-rr-aac" . "https://www.wxxi.org/sites/default/files/rr-aac-triton.m3u")
     ("triton-weos-aac" . "https://www.wxxi.org/sites/default/files/weos-aac-triton.m3u")
     ("triton-with-aac" . "https://www.wxxi.org/sites/default/files/with-aac-triton.m3u")
     ("triton-wrur-aac" . "https://www.wxxi.org/sites/default/files/wrur-aac-triton.m3u")) t)
 '(global-command-log-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
